# [START cloudbuild]
steps:
# Este paso ejecuta las pruebas unitarias de la aplicación.
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && python test_app.py -v'

# Este paso construye la imagen del contenedor.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/hello-cloudbuild:$SHORT_SHA'
  - '.'

# Este paso enpuja la imagen a Container Registry
# PROJECT_ID y SHORT_SHA son variables de entorno que ya estan
# predefinidas en Cloud Build, ete las reemplaza con sus valores correspondientes.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/hello-cloudbuild:$SHORT_SHA'
# [END cloudbuild]